# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eef4e2ed5be71d8fa6b7d112e63d1ce8b5af54fe3759005ef5c8262bfa097741a4499ce5c928991e926e2fec362c2ac54195e8a3c79f48545a22c19efdd17a92

test:
  secret_key_base: 976aaf9163f7383067fc751d51e57cc1320d5d6864889827b00374659de15e3f4ca6b24a0b17250e9789b7742154d873c17acf638272d0d509b5960d00d24ada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
